### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by xDigital** [llazzaro/analyzerstrategies#1]
Hi,

I believe that you have unresolved dependencies on TA-Lib. They do now work and end with gcc error. Hence making any further development on your project a futile exercise.

Best Regards.

**Comment by llazzaro** [comment]
Hi,
This project is very complex to get it to work. Remember this is open source and free. 
If you think this is futile, go and pay thousands of dollars for a commercial version.

**Comment by MaximusIndus** [comment]
If you thought. Donate. Please... Let's do it together...  But not donate...
